### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by rom1v** [JakeWharton/Telecine#166]
I cloned the current master (0e4ee6a39d3a929e2ab971451a9eec89cac88bff).

Then:

    gradle installDebug

It builds and install the app on the phone (a Nexus 5 with AOSP 6.0.1). I click on "Telecine Debug" in the app list, I get _"Telecine Debug" has stopped"_.

Here is the logcat:

```
I ActivityManager: Process com.jakewharton.telecine.debug (pid 3310) has died
W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.jakewharton.telecine.debug/com.jakewharton.telecine.TelecineActivity (has extras)} from uid 10008 on display 0
D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
I ActivityManager: Start proc 3411:com.jakewharton.telecine.debug/u0a64 for activity com.jakewharton.telecine.debug/com.jakewharton.telecine.TelecineActivity
I art     : Late-enabling -Xcheck:jni
D AudioFlinger: mixer(0xb4040000) throttle end: throttle time(7)
W System  : ClassLoader referenced unknown path: /data/app/com.jakewharton.telecine.debug-2/lib/arm
I art     : Rejecting re-init on previously-failed class java.lang.Class<com.jakewharton.telecine.TelecineTileService>
I art     : Rejecting re-init on previously-failed class java.lang.Class<com.jakewharton.telecine.TelecineTileService>
D AndroidRuntime: Shutting down VM

E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.jakewharton.telecine.debug, PID: 3411
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jakewharton/telecine/TelecineTileService;
E AndroidRuntime: 	at com.jakewharton.telecine.DaggerTelecineComponent.initialize(DaggerTelecineComponent.java:192)
E AndroidRuntime: 	at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:97)
E AndroidRuntime: 	at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:20)
E AndroidRuntime: 	at com.jakewharton.telecine.DaggerTelecineComponent$Builder.build(DaggerTelecineComponent.java:277)
E AndroidRuntime: 	at com.jakewharton.telecine.TelecineApplication.onCreate(TelecineApplication.java:22)
E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jakewharton.telecine.TelecineTileService" on path: DexPathList[[zip file "/data/app/com.jakewharton.telecine.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.jakewharton.telecine.debug-2/lib/arm, /vendor/lib, /system/lib]]
E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E AndroidRuntime: 	... 15 more
E AndroidRuntime: 	Suppressed: java.lang.NoClassDefFoundError: com.jakewharton.telecine.TelecineTileService
E AndroidRuntime: 		at dalvik.system.DexFile.defineClassNative(Native Method)
E AndroidRuntime: 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
E AndroidRuntime: 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
E AndroidRuntime: 		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
E AndroidRuntime: 		... 17 more
E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.jakewharton.telecine.TelecineTileService
E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E AndroidRuntime: 		... 16 more
E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
W ActivityManager:   Force finishing activity com.jakewharton.telecine.debug/com.jakewharton.telecine.TelecineActivity
I OpenGLRenderer: Initialized EGL, version 1.4
W ActivityManager: Activity pause timeout for ActivityRecord{65e5332 u0 com.jakewharton.telecine.debug/com.jakewharton.telecine.TelecineActivity t2000 f}
```

**Comment by TonyTangAndroid** [comment]
Any thoughts on how to fix this issue?
