### ISSUE TITLE
error at touch the clock area

### ISSUE THREAD

**Issue by binsee** [JakeWharton/Telecine#45]
```
Process: com.jakewharton.telecine
Flags: 0xc8be44
Package: com.jakewharton.telecine v1020000 (1.2.0)
Build: OPPO/X9007/X9007:5.0/LRX21M/1426582430:user/release-keys

java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:160)
	at com.jakewharton.telecine.RecordingSession$3.doInBackground(RecordingSession.java:321)
	at com.jakewharton.telecine.RecordingSession$3.doInBackground(RecordingSession.java:318)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

```

**Comment by jaredsburrows** [comment]
How do you reproduce this? Do you just "touch" the clock?

**Comment by binsee** [comment]
@jaredsburrows yes.

**Comment by jaredsburrows** [comment]
@binsee I just tried to reproduce this with the Google Play version and cannot. However, when I click on the "clock", it "stops" recording.

**Comment by jaredsburrows** [comment]
@binsee Can you give more details? or can we close this @JakeWharton.

**Comment by binsee** [comment]
Sorry, it's been a long time not to pay attention to GitHub. Now the phone is replaced by CM13 system, this problem has not been tested again. Please close this.
