### ISSUE TITLE
Many DeadObjectExceptions showing up in LogCat

### ISSUE THREAD

**Issue by techehcet** [JakeWharton/Telecine#49]
Every time a recording is stopped, a number of DeadObjectExceptions are written to logcat. The number of these is ever-increasing (until next reboot). It increments each time Telecine (or any other app using MediaProjection) is launched (killed?).  Now, maybe this can simply be ignored. But, having, sometimes, hundreds of these messages written each time the recording is stopped, is rather annoying at least.

See here: https://code.google.com/p/android/issues/detail?id=81152

Confirmed on 5.1.1 (Nexus 5)

Any ideas on how to work around this?

05-23 12:46:16.623      725-725/? W/MediaProjectionManagerService﹕ Failed to notify media projection has stopped
    android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:496)
            at android.media.projection.IMediaProjectionCallback$Stub$Proxy.onStop(IMediaProjectionCallback.java:75)
            at com.android.server.media.projection.MediaProjectionManagerService$ClientStopCallback.run(MediaProjectionManagerService.java:614)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at com.android.server.SystemServer.run(SystemServer.java:269)
            at com.android.server.SystemServer.main(SystemServer.java:170)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by JakeWharton** [comment]
I can't see how there would be anything to fix this that an application could do. The problem is entirely in the OS from what I gather on that issue and the stack trace. The issue itself says that _any_ use of the recording APIs causes this.

It wouldn't be the first time there was platform bugs around recording: http://b.android.com/159196

Going to close since there's nothing I can do. I'll keep an eye on that issue, though, in case any news of updates or workarounds comes about.

**Comment by techehcet** [comment]
Ok, fair enough. Out of interest, is this problem also occurring in M Preview?
