### ISSUE TITLE
MediaRecorder prepare fails.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/Telecine#6]
```
java.lang.RuntimeException: Unable to prepare MediaRecorder.
        at com.jakewharton.telecine.RecordingSession.startRecording(RecordingSession.java:179)
        at com.jakewharton.telecine.RecordingSession.access$100(RecordingSession.java:47)
        at com.jakewharton.telecine.RecordingSession$1.onStart(RecordingSession.java:111)
        at com.jakewharton.telecine.OverlayView.startRecording(OverlayView.java:147)
        at com.jakewharton.telecine.OverlayView.access$300(OverlayView.java:31)
        at com.jakewharton.telecine.OverlayView$5$1$1.run(OverlayView.java:163)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
        at android.view.Choreographer.doCallbacks(Choreographer.java:599)
        at android.view.Choreographer.doFrame(Choreographer.java:559)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:781)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5466)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:733)
Caused by: java.io.IOException: prepare failed.
        at android.media.MediaRecorder._prepare(MediaRecorder.java:-2)
        at android.media.MediaRecorder.prepare(MediaRecorder.java:742)
        at com.jakewharton.telecine.RecordingSession.startRecording(RecordingSession.java:177)
        at com.jakewharton.telecine.RecordingSession.access$100(RecordingSession.java:47)
        at com.jakewharton.telecine.RecordingSession$1.onStart(RecordingSession.java:111)
        at com.jakewharton.telecine.OverlayView.startRecording(OverlayView.java:147)
        at com.jakewharton.telecine.OverlayView.access$300(OverlayView.java:31)
        at com.jakewharton.telecine.OverlayView$5$1$1.run(OverlayView.java:163)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
        at android.view.Choreographer.doCallbacks(Choreographer.java:599)
        at android.view.Choreographer.doFrame(Choreographer.java:559)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:781)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5466)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:733)
```
```
1420755940708 D Attempting to acquire permission to screen capture.
1420755940748 D Acquired permission to screen capture. Starting service.
1420755940752 D Starting up!
1420755940764 D Adding overlay view to window.
1420755946112 D Starting screen recording...
1420755946119 D Video size: 100%
1420755946147 I Output file '/storage/emulated/0/Movies/Telecine/Telecine_2015-01-08-14-25-46.mp4'.
```
```
apiLevel
21
batteryLevel
0.63
charging
false
freeDisk
27374383104.0
freeMemory
182602840
jailbroken
false
locale
en_US
locationStatus
allowed
manufacturer
HTC
model
HTC One
networkAccess
wifi
orientation
portrait
osBuild
LRX22C.H3 release-keys
osName
android
osVersion
5.0.1
screenDensity
3
screenResolution
1920x1080
totalMemory
201326592
```

**Comment by spectrl** [comment]
Try explicitly setting the frame rate using setCaptureRate() on the MediaRecorder.

**Comment by JakeWharton** [comment]
To what value? Just 60?

**Comment by spectrl** [comment]
30 seems to work pretty well.

**Comment by monxalo** [comment]
Also occuring on a Nexus 7 with latest Lollipop.

**Comment by jaredsburrows** [comment]
I am seeing error running Android 5.0.2.

**Comment by labnol** [comment]
@JakeWharton - Getting a similar error on Android 5.0.1 on Nexus 4.

**Comment by gabin8** [comment]
@jaredsburrows how about setting frame rate based on device characters or so on ?

**Comment by jaredsburrows** [comment]
@gabin8 What do you mean by device characters?

**Comment by gabin8** [comment]
I mean may be try to set frame rate 60 if the device allows it and works smooth. Or to define that value manually as a set of options (e.g. 24, 30, 60 etc.)

**Comment by jaredsburrows** [comment]
@gabin8 Yes, that is a possibility, I am just showing @JakeWharton what I did to allow it to work on other Android 5.0+ devices. Also, I am not sure if he wants to add that capability in his example application.

**Comment by gabin8** [comment]
@JakeWharton When are you expecting to roll out the fix?

**Comment by jaredsburrows** [comment]
@gabin8 Seeing that @JakeWharton is on Github almost everyday and has not responded. It seems that sometimes he just doesn't respond at all, maybe not a priority. He works a lot like Google does with Open Source projects: he puts it out there and then does not touch it again or at least not for a while.

**Comment by JakeWharton** [comment]
Frame rate is now set to 30. Size is being tracked by #17.
